### ISSUE TITLE
Saved Games should show games sorted from Newest to Oldest

### ISSUE THREAD

**Issue by tolgabalci** [tolgabalci/StoryPointGames#10]
Currently the games are sorted oldest to newest.

**Comment by oscorp82** [comment]
Resolved, now showing in reverse order.

#06b995f

**Comment by oscorp82** [comment]
Reopening issue.

**Comment by bemch24** [comment]
Saved games sort gets set incorrectly when selecting a card in an active game and another session has the saved games open.
