### ISSUE TITLE
Not all users show on the Players list

### ISSUE THREAD

**Issue by oscorp82** [tolgabalci/StoryPointGames#33]
Please see attached screenshot.

![missingusers](https://user-images.githubusercontent.com/25487053/31682202-641b8ef4-b347-11e7-887b-ab3717f60991.jpg)

**Comment by tolgabalci** [comment]
Looking at this issue in action:
When the user first logs in to the game, they can see the game, but their name does not show in the list of users (see Brian's Screenshot) and when looking at the database, the userkey is *NOT PRESENT*:
/game/{gamekey}/users/{*userkey*}

Once the user votes, their *userkey* gets created under the users node with only the voted property:
![image](https://user-images.githubusercontent.com/2467618/32511587-371c0a1a-c3c2-11e7-93ed-c82e7007b689.png)

**Comment by bemch24** [comment]
Added addUserToGame in constructer of game component, that way any time a game is opened the user is added regardless of where the component is called from.
